version: '3.9'

services:

  production-service:
    build: .
    ports:
      - "80:80"

  dev-service:
    image: node:alpine
    volumes:
      - .:/santini-gen
    ports:
      - "80:80"

    command: sh -c "cd /santini-gen && npm ci && npm start"  

  
